spring:
    #数据库配置信息
    datasource:
        # 引入druid
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/jpa?characterEncoding=utf8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: admin
        #druid连接池配置
        #最大活跃数
        maxActive: 20
        #初始化连接数量
        initialSize: 5
        #连接最大超时时间
        maxWait: 60000
        #打开PSCache,并且指定每个连接PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        #通过connectionProperties属性来打开mergeSql功能;慢SQL记录
        #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select '1' from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
        filters: stat, wall, log4j
    #JPA配置
    jpa:
        database: MySQL
        format_sql: true
        show_sql: true
        hibernate:
            ddl-auto: update
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #设置编码格式
    http:
        encoding:
            force: true
            charset: UTF-8
            enabled: true
    multipart:
        max-file-size: 10MB
        max-request-size: 20MB
#web容器的端口号和编码配置
server:
    tomcat:
        uri-encoding: UTF-8
    #修改Tomcat端口号,默认端口号8080
    port: 8084